{% set name = "libzenohcxx" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eclipse-zenoh/zenoh-cpp/archive/refs/tags/{{ version }}.tar.gz
    sha256: ffd3cb8c8263f842479c93c0e380583a2749f2c99cff0e46e5e81f1de47cb793
    patches:
      - 136.patch
      - disable_tests_examples_and_docs.patch
      - disable_zenoh_pico.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - libzenohc {{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/include/zenoh.hxx  # [unix]
    - if not exist %LIBRARY_PREFIX%\\include\\zenoh.hxx exit 1  # [win]
    # --disable-double-find passed as a workaround for https://github.com/eclipse-zenoh/zenoh-cpp/pull/232
    # We need to first call find_package(zenohc) otherwise zenohcxx::zenohc::lib is not defined
    - cmake-package-check zenohc zenohcxx --targets zenohcxx zenohcxx::zenohc::lib --disable-double-find
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/eclipse-zenoh/zenoh-cpp
  license: Apache-2.0 OR EPL-2.0
  license_file: LICENSE
  summary: C++ API for zenoh

extra:
  feedstock-name: zenoh-cpp
  recipe-maintainers:
    - traversaro
