schema_version: 1

context:
  name: libzenohcxx
  version: "1.10.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/eclipse-zenoh/zenoh-cpp/archive/refs/tags/${{ version }}.tar.gz
    sha256: 64d3c315c4fdfa54b4d96ee27ee2b3d98320b0fb289402fff9d7a99bc513528e
    patches:
      - nowerror.patch

build:
  # See https://github.com/conda-forge/zenoh-c-feedstock/issues/37
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - libzenohc ${{ version }}.*

tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - if: unix
        then: test -f ${PREFIX}/include/zenoh.hxx
      - if: win
        then: if not exist %LIBRARY_PREFIX%\\include\\zenoh.hxx exit 1
      - cmake-package-check zenohc zenohcxx --targets zenohcxx zenohcxx::zenohc

about:
  license: Apache-2.0 OR EPL-2.0
  license_file: LICENSE
  summary: C++ API for zenoh
  homepage: https://github.com/eclipse-zenoh/zenoh-cpp

extra:
  feedstock-name: zenoh-cpp
  recipe-maintainers:
    - traversaro
